repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff-format
        name: ruff-format
        files: ^anki-card-generator/
      - id: ruff
        name: ruff-check
        args: [--fix]
        files: ^anki-card-generator/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy
        args: [--strict]
        files: ^anki-card-generator/src/
        additional_dependencies:
          - google-generativeai>=0.8.3
          - types-requests
